# Generated by Django 5.1.5 on 2025-03-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedmaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetail',
            name='car_license_plate',
            field=models.CharField(max_length=20),
        ),
    ]
