# Generated by Django 5.1.5 on 2025-03-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedmaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user_receipt',
            field=models.ImageField(upload_to='receipts/'),
        ),
    ]
