# Generated by Django 5.1.5 on 2025-03-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedmaster', '0002_alter_payment_user_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
